### ISSUE TITLE
No puedo levantar el contenedor

### ISSUE THREAD

**Issue by tho7o** [Mikroways/docker-rsnapshot#1]
Hola,

He intentado levantar el contenedor vía el siguiente compose:

```
version: "3.7"

services:
  rsnapshot:
    container_name: rsnapshot
    image: gafonso21/docker-rsnapshot
    volumes:
      - ./hola:/hola
    environment:
      BACKUP_DIRECTORIES: |
                   /hola/  /home

    command: ["rsnapshot", "hourly"]
```

Pero me suelta el siguiente error:

```
Creating network "rsnap_default" with the default driver
Recreating rsnapshot ... done                                                                                           Attaching to rsnapshot
rsnapshot    | ----------------------------------------------------------------------------
rsnapshot    | rsnapshot encountered an error! The program was invoked with these options:
rsnapshot    | /usr/bin/rsnapshot hourly
rsnapshot    | ----------------------------------------------------------------------------
rsnapshot    | ERROR: /etc/rsnapshot.conf on line 36:
rsnapshot    | ERROR: backup /hola/ /home - no destination path specified for backup point
rsnapshot    | ERROR: ---------------------------------------------------------------------
rsnapshot    | ERROR: Errors were found in /etc/rsnapshot.conf,
rsnapshot    | ERROR: rsnapshot can not continue. If you think an entry looks right, make
rsnapshot    | ERROR: sure you don't have spaces where only tabs should be.
```

¿Qué puede estar pasando?
