### ISSUE TITLE
rsnapshot exited with code 0

### ISSUE THREAD

**Issue by tho7o** [Mikroways/docker-rsnapshot#2]
Hola, muchas gracias por actualizar tu repo. 

He estado probando el siguiente compose, basado en tu imagen:

```
version: '3.7'
services:
  rsnapshot:
    container_name: rsnapshot
    image: mikroways/docker-rsnapshot
    volumes:
      - ./www/html/data/:/data
      - ./backups:/var/rsnapshot
    environment:
      RETAIN_HOURLY: 4
      RETAIN_DAILY: 7
      RETAIN_WEEKLY: 4
      RETAIN_MONTHLY: 6
      BACKUP_DIRECTORIES: "/data/:bkp/"
```
Si le tiro un "docker-compose logs -f" me dice los siguiente:

```
Attaching to rsnapshot
rsnapshot    | Starting rnsapshot with config file:
rsnapshot    | #################################################
rsnapshot    | # rsnapshot.conf - rsnapshot configuration file #
rsnapshot    | #################################################
rsnapshot    | #                                               #
rsnapshot    | # PLEASE BE AWARE OF THE FOLLOWING RULES:       #
rsnapshot    | #                                               #
rsnapshot    | # This file requires tabs between elements      #
rsnapshot    | #                                               #
rsnapshot    | # Directories require a trailing slash:         #
rsnapshot    | #   right: /home/                               #
rsnapshot    | #   wrong: /home                                #
rsnapshot    | #                                               #
rsnapshot    | #################################################
rsnapshot    |
rsnapshot    | #######################
rsnapshot    | # CONFIG FILE VERSION #
rsnapshot    | #######################
rsnapshot    | config_version   1.2
rsnapshot    | snapshot_root    /var/rsnapshot/
rsnapshot    |
rsnapshot    | cmd_ssh  /usr/bin/ssh
rsnapshot    | cmd_cp   /bin/cp
rsnapshot    | cmd_rm   /bin/rm
rsnapshot    | cmd_rsync        /usr/bin/rsync
rsnapshot    | cmd_logger       /usr/bin/logger
rsnapshot    | verbose  2
rsnapshot    | loglevel 3
rsnapshot    | logfile  /var/log/rsnapshot.log
rsnapshot    | lockfile /var/run/rsnapshot.pid
rsnapshot    | retain   hourly  4
rsnapshot    | retain   daily   7
rsnapshot    | retain   weekly  4
rsnapshot    | retain   monthly 6
rsnapshot    | retain   yearly  2
rsnapshot    | rsync_short_args -aL
rsnapshot    | rsync_long_args  --delete --numeric-ids --relative --delete-excluded
rsnapshot    | backup   /data/  bkp/
rsnapshot    | Starting rnsapshot:
rsnapshot exited with code 0
```

Como ves, se sale y deja un `rsnapshot exited with code 0`

Sí me genera el backup `hourly.0`, pero no sé si seguirá haciendo backups ya que no me figura como un contenedor que está "vivo", cuando hago un `docker ps`

¿Qué puede estar pasando?
